Completed css-canvas-medical exercise- Dulce Herrera
dulceherrera/c0622-code-solutions pull request #21
Opened 2022-07-05 03:07 UTC by dulceherrera

<img width="795" alt="Screen Shot 2022-07-04 at 8 01 37 PM" src="https://user-images.githubusercontent.com/97363006/177241587-ed826eab-7dd3-4661-ba59-0a6268db1799.png">

2022-07-05 17:30 UTC, codingcodymiller requested changes
Hey Dulce! A couple things:
1. Your horizontal alignment of the content does not seem to match the example in multiple places
2. Your screenshot does not show off multiple sections of the output

Please revise and submit new screenshots with your revision.

2022-07-27 03:39 UTC, dulceherrera commented
https://user-images.githubusercontent.com/97363006/181155607-f4cbc8b6-8eca-411d-85bc-3febb20595a2.mp4

2022-07-27 03:51 UTC, dulceherrera commented
<img width="977" alt="Screen Shot 2022-07-26 at 8 50 40 PM" src="https://user-images.githubusercontent.com/97363006/181156939-dafde3d3-5549-4862-b692-76a4bae96519.png">

2022-07-27 16:46 UTC, codingcodymiller approved these changes

2022-07-27 16:56 UTC, merged